plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.lucasmoraist'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('modelMapperVersion', "3.2.6")
	set('openApiVersion', "3.0.2")
	set('jwtVersion', "4.5.2")
	set('awsSdkVersion', '2.44.9')
}

dependencies {
    // Spring
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Database
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'
	implementation 'org.springframework.boot:spring-boot-h2console'

	// Flyway
	implementation 'org.flywaydb:flyway-database-postgresql'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
    testImplementation 'org.springframework.boot:spring-boot-starter-flyway-test'

	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'

    // Cache
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'com.github.codemonstur:embedded-redis:1.4.3'

	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'

	// Logging
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    testImplementation 'io.github.hakky54:logcaptor:2.12.6'

    // OpenAPI
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${openApiVersion}"

	// ModelMapper
    implementation "org.modelmapper:modelmapper:${modelMapperVersion}"

    // Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation "com.auth0:java-jwt:${jwtVersion}"
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'

    // S3
    implementation "software.amazon.awssdk:s3:${awsSdkVersion}"

    // PDF
    implementation 'org.apache.pdfbox:pdfbox:3.0.3'
}

bootJar {
    layered {
        enabled = true
    }
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
	testLogging {
        events "passed", "skipped", "failed"
    }
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
}
