services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_db
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge